//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrare_pensiune
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTable
    {
        public int BId { get; set; }
        public System.DateTime BDate { get; set; }
        public int BRoom { get; set; }
        public int User_Id { get; set; }
        public System.DateTime DateIn { get; set; }
        public System.DateTime DateOut { get; set; }
        public int Amount { get; set; }
    
        public virtual RoomTable RoomTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
