//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrare_pensiune
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomTable()
        {
            this.BookingTable = new HashSet<BookingTable>();
        }
    
        public int RId { get; set; }
        public string RName { get; set; }
        public int RCategory { get; set; }
        public string RLocation { get; set; }
        public string RCost { get; set; }
        public string RRemarks { get; set; }
        public string Status { get; set; }
        public string PretAtv { get; set; }
        public string PretMasa { get; set; }
        public string PretGhid { get; set; }
        public string PretBicicleta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTable> BookingTable { get; set; }
        public virtual CategoryTable CategoryTable { get; set; }
    }
}
